schedule/urls.py
from django.conf.urls.defaults import *
from stswim.schedule.forms import AddLessonForm1, AddLessonForm2, AddLessonForm3, AddLessonWizard
from stswim.schedule.models import Household, Parent, Student, Season

seasons = {
	'queryset': Season.objects.all(),
}

urlpatterns = patterns('',
	
	url(r'^season/$', 'stswim.schedule.views.viewseason', name='view_currentseason'),
	url(r'^season/add/$', 'stswim.schedule.admin_views.addseason', name='add_season'),
	url(r'^season/(?P<season_id>\d+)/view/month/(?P<display_month>\d+)/$', 'stswim.schedule.views.viewseason', name='view_season_bymonth'),
	url(r'^season/(?P<season_id>\d+)/view/$', 'stswim.schedule.views.viewseason', name='view_season'),
	url(r'^season/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/view/$', 'stswim.schedule.views.viewday', name='view_season_byday'),
	url(r'^season/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/close/$', 'stswim.schedule.admin_views.closeday', name='close_day'),
	url(r'^season/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/open/$', 'stswim.schedule.admin_views.openday', name='open_day'),
	
	(r'^lessonslot/add/$', 'stswim.schedule.admin_views.addlessonslot'),
	url(r'^lessonslot/(?P<lessonslot_id>\d+)/view/$', 'stswim.schedule.admin_views.viewlessonslotdetail', name='view_lessonslot'),
	(r'^lessonslot/(?P<lessonslot_id>\d+)/close/$', 'stswim.schedule.admin_views.closelessonslot'),
	(r'^lessonslot/(?P<lessonslot_id>\d+)/open/$', 'stswim.schedule.admin_views.openlessonslot'),
	#(r'^lessonslot/(?P<lessonslot_id>\d+)/addlesson/$', 'stswim.schedule.admin_views.addlesson'),
	
	url(r'^lesson/add/$', AddLessonWizard([AddLessonForm1, AddLessonForm2, AddLessonForm3]), name="add_lesson"),
	url(r'^lesson/(?P<lesson_id>\d+)/addstudent/$', 'stswim.schedule.admin_views.addstudenttolesson', name="add_studenttolesson"),
	url(r'^lesson/(?P<lesson_id>\d+)/removestudent/(?P<student_id>\d+)$', 'stswim.schedule.admin_views.removestudentfromlesson', name="remove_studentfromlesson"),
	url(r'^lesson/(?P<lesson_id>\d+)/delete/$', 'stswim.schedule.admin_views.deletelesson', name="delete_lesson"),
	url(r'^lesson/(?P<lesson_id>\d+)/edit/$', 'stswim.schedule.admin_views.editlesson', name="edit_lesson"),
	
	
	url(r'^household/(?P<household_id>\d+)/view/$', 'stswim.schedule.admin_views.viewhousehold', name='view_household'),
	url(r'^household/(?P<household_id>\d+)/addparent/$', 'stswim.accounts.admin_views.addparent', name='add_parenttohousehold'),
	url(r'^household/(?P<household_id>\d+)/addstudent/$', 'stswim.schedule.admin_views.addstudent', name='add_studenttohousehold'),

	url(r'^parents/$', 'stswim.schedule.admin_views.listparents', name='list_parents'),
	url(r'^parent/add/$', 'stswim.accounts.admin_views.addparent', name='add_parent'),
	url(r'^parent/(?P<parent_id>\d+)/view/$', 'stswim.schedule.admin_views.viewparent', name='view_parent'),
	url(r'^parent/(?P<parent_id>\d+)/edit/$', 'stswim.schedule.admin_views.editparent', name='edit_parent'),
	
	url(r'^students/$', 'stswim.schedule.admin_views.liststudents', name='list_students'),
	url(r'^student/(?P<student_id>\d+)/view/$', 'stswim.schedule.admin_views.viewstudent', name='view_student'),
	url(r'^student/(?P<student_id>\d+)/edit/$', 'stswim.schedule.admin_views.editstudent', name='edit_student'),
	
	url(r'^register/$', 'stswim.schedule.views.regorlogin', name='regorlogin'),
	url(r'^resetpass/$', 'stswim.schedule.views.parentresetpassword', name='parent_resetpassword'),
	url(r'^parentdashboard/$', 'stswim.schedule.views.parentdashboard', name='parent_dashboard'),
	url(r'^parentdashboard/addstudent$', 'stswim.schedule.views.parentregisterstudent', name='parent_registerstudent'),
	url(r'^parentdashboard/requestlesson$', 'stswim.schedule.views.requestlesson', name='parent_requestlesson'),
	
	url(r'^manage/$', 'stswim.schedule.admin_views.manageschedule', name='manage_schedule'),
)

urlpatterns += patterns('django.views.generic.list_detail',
	url(r'^seasons/$', 'object_list', seasons, name='list_seasons'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns('django.views.generic.simple',
		       
		       (r'^$', 'direct_to_template', {'template': 'main1col.html'}), #Catch root url to homepage
		       (r'^manage/$', 'redirect_to', {'url': '/schedule/manage/'}),
)

urlpatterns += patterns('',
		       # Example:
		       # (r'^stswim/', include('stswim.foo.urls')),
		   
		       #urls.py includes
		       (r'^accounts/', include('stswim.accounts.urls')),
		       (r'^schedule/', include('stswim.schedule.urls')),
			   (r'^register/$', 'stswim.schedule.views.regorlogin'),
		
			   (r'^login/$', 'stswim.schedule.views.regorlogin'),
			   (r'^logout/$', 'stswim.accounts.views.logout_view'),
		       
		       #Pages app admin urls
		       (r'^admin/pages/page/$', 'stswim.pages.admin_views.list_pages'),
		       (r'^admin/pages/page/(?P<hnode_id>\d+)/up/$', 'stswim.pages.admin_views.up'),
		       (r'^admin/pages/page/(?P<hnode_id>\d+)/down/$', 'stswim.pages.admin_views.down'),
		       
		       # Built-In Admin
		       (r'^admin/', include(admin.site.urls)),

		       # Handle static files
		       (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/Users/stephen/Projects/stswim/media/'}),
		       
		       #content pages
		       #(r'^(?P<page_slug>\w+)/$', 'pages.views.details'),
		       (r'^(?P<full_slug>(.*))/$', 'stswim.pages.views.details'),
			   
)



schedule/models.py
from django.forms import ModelForm
from django.db import models
from django.contrib.localflavor.us.models import USStateField, PhoneNumberField
from django.contrib.auth.models import User

SEX_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)

LESSON_TYPES = (
    ('Private', 'Private'),
    ('Semi-Private', 'Semi-Private'),
    ('Small-Group', 'Small-Group'),
    ('Large-Group', 'Large-Group'),
)

LESSONSLOT_STATUS = (
    ('Open', 'Open'),
    ('Closed', 'Closed'),
    ('Pending', 'Pending'),
    ('Booked', 'Booked'),
)

LESSON_STATUS = (
    ('Booked', 'Booked'),
    ('Open', 'Open'),
	('No Show', 'No Show'),
	('Missed', 'Missed'),
	('Make Up', 'Make Up'),
	('Late', 'Late'),
    ('Pending', 'Pending'),
    ('Cancelled', 'Cancelled'),
)

EMPLOYEE_STATUS = (
	('Active', 'Active'),
	('Inactive', 'Inactive'),
)

STATUS = (
	('0', 'Inactive'),
	('1', 'Active'),
)

class Household(models.Model):
    creation_date = models.DateField()

    class Meta:
        permissions = (
                ("can_viewhousehold", "Can view households"),
                )

class Parent(models.Model):
    user = models.ForeignKey(User, unique=True, editable=False, blank=True, null=True)
    household = models.ForeignKey(Household, editable=False)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(blank=True, null=True)
    phone_number = PhoneNumberField()
    address = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=50)
    state = USStateField()
    zip_code = models.CharField(max_length=5)
    has_registrationform = models.BooleanField("Has registration form", blank=True)
    
    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name)
    
    class Meta:
        ordering = ['last_name']
        permissions = (
                ("can_viewparents", "Can view parents"),
                )
        
class Student(models.Model):
    household = models.ForeignKey(Household, editable=False)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    birth_date = models.DateField()
    sex = models.CharField(max_length=10, choices=SEX_CHOICES)
    has_liabilityform = models.BooleanField("Has liability form", blank=True)
    
    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name)
    
    class Meta:
        ordering = ['last_name']
        permissions = (
                ("can_viewstudents", "Can view students"),
                )

class Employee(models.Model):
    status =  models.CharField(choices=EMPLOYEE_STATUS, default='Active', max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    birth_date = models.DateField()
    phone_number = PhoneNumberField()
    address = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=50)
    state = USStateField()
    zip_code = models.CharField(max_length=5)
    
    def __unicode__(self):
        return '%s' % (self.first_name)

class Season(models.Model):
    status = models.CharField(choices=STATUS, max_length=30)
    name = models.CharField(max_length=30)
    start_date = models.DateField()
    end_date = models.DateField()
    
    def __unicode__(self):
        return '%s' % (self.name)
        
    class Meta:
        ordering = ['start_date']
        permissions = (
                ("can_viewfullschedule", "Can view full schedule"),
                )

class Lesson(models.Model):
    lesson_type = models.CharField(choices=LESSON_TYPES, max_length=30)
    students = models.ManyToManyField(Student, blank=True)
    status = models.CharField(choices=LESSON_STATUS, max_length=30)
    
    def __unicode__(self):
        return '%s %s' % (LessonSlot.objects.get(lesson__exact = self).start_datetime, LessonSlot.objects.get(lesson__exact = self).start_time)
    
    class Meta:
        permissions = (
                ("can_booklesson", "Can book lessons"),
                )
    
    def cancel(self):
        lessonslot = self.lessonslot_set.all()[0]
        lessonslot.status = 'Open'
        lessonslot.lesson = None
        lessonslot.save()
        
        self.delete()
    
    def removestudent(self, student):
        self.students.remove(student)
        self.save()

    def addstudent(self, student):
        self.students.add(student)
        self.save()

#Lesson Slots are time slots that lessons fit into. Slots can be open, closed, booked etc...        
class LessonSlot(models.Model):
    season = models.ForeignKey(Season, null=True, blank=True)
    start_datetime = models.DateTimeField()
    start_time = models.TimeField()
    end_datetime = models.DateTimeField()
    end_time = models.TimeField()
    weekday = models.IntegerField()
    lesson = models.ForeignKey(Lesson, null=True, blank=True)
    instructor = models.ForeignKey(Employee, null=True, blank=True)
    status = models.CharField(choices=LESSONSLOT_STATUS, max_length=30)
    
    class Meta:
        ordering = ['start_datetime']
    
    def __unicode__(self):
        return '%s/%s/%s %s' % (self.start_datetime.month, self.start_datetime.day, self.start_datetime.year, self.start_datetime.time())
        
    def close(self):
        self.status = 'Closed'
        self.save()
    
    def open(self):
        self.status = 'Open'
        self.save()

schedule/templates/schedule/base_manage.html
{% extends 'main2col.html' %}

{% block title %}Sea Turtle Swim School Schedule Management System{% endblock %}
{% block external %}<script src="/media/js/search.js" type="text/javascript"></script>{% endblock %}
{% block col1 %}	
	<a href="{% url stswim.schedule.admin_views.manageschedule %}">Dashboard</a><br /><br />
	<h3>View</h3>
	<ul class="management_menu">
		{% if perms.schedule.can_viewparents %}
			<li><a href="{% url list_parents %}">Parents</a></li>
		{% endif %}
		{% if perms.schedule.can_viewstudents %}
			<li><a href="{% url list_students %}">Students</a></li>
		{% endif %}
		<li><a href="{% url view_currentseason  %}">Current Season</a></li>
		<li><a href="{% url list_seasons %}">Seasons</a></li>
	</ul>
	{% if perms.schedule.can_addparent or perms.schedule.can_booklesson or perms.schedule.can_addlessonslot or perms.schedule.can_addseason %}
		<h3>Tools</h3>
		<ul class="management_menu">
			{% if perms.schedule.can_addparent %}
				<li><a href="{% url add_parent %}">Add Parent</a></li>
			{% endif %}
			{% if perms.schedule.can_booklesson %}
				<li><a href="{% url add_lesson %}">Book Lesson</a></li>
			{% endif %}
			{% if perms.schedule.can_addlessonslot %}
				<li><a href="{% url stswim.schedule.admin_views.addlessonslot %}">Add Lesson Slots</a></li>
			{% endif %}	
			{% if perms.schedule.can_addseason %}
				<li><a href="{% url stswim.schedule.admin_views.addseason %}">Add Season</a></li>
			{% endif %}
		{% endif %}
	
{% endblock %}

{% block col2 %}
	<p class="floatright">
		{% if user.is_authenticated %}
			Hello {{ user.first_name }}! <a href="{% url logout %}">logout</a>
		{% else %}
			Please <a href="{% url login %}">Login</a>
		{% endif %}
	</p><br />
	
	{% block manage_content %}
	<h2>Management Dashboard</h2>
		<div id="people-search">
			<h3>People Search</h3>
			<form id="search-form" method="get" action=".">
				<p>
				{{ form }}
				<input type="submit" value="search" />
				</p>
			</form>
			
			<div id="search-results">
			{% if show_results %}
				{% include 'schedule/people_list.html' %}
			{% endif %}
			</div>
		</div>
		
	{% if todayslessonslots %}
		<h3>Today's Lessons:</h3>
		 <table class="data">
		 <tr><th>Time</th><th>Status</th><th>Type</th><th>Student(s)</th><th>Instructor</th></tr>
		 	{% for lessonslot in todayslessonslots %}
		 		<tr class="{% cycle even,odd %}">
		 			<td><a href="{% url view_lessonslot lessonslot_id=lessonslot.id %}">{{lessonslot.start_datetime|time:"g:i a"}}</a></td>
		 			<td>{{lessonslot.lesson.status}}</td>
					<td>{{lessonslot.lesson.lesson_type}}</td>
		 			<td>{% for student in lessonslot.lesson.students.all %}{{student.first_name}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
		 			<td>{{lessonslot.instructor}}</td>
		 		</tr>
		 	{% endfor %}
		 </table>
	{% else %}
		<h3>No Lessons Today</h3>
	{% endif %}
			
	{% endblock %}

	
{% endblock %}

schedule/templates/schedule/dayview.html
{% extends 'schedule/base_manage.html' %}

{% block title %}Sea Turtle Swim School Schedule{% endblock %}


{% block manage_content %}
<h3>Lessons for {{display_date|date:"m/d/y"}}:</h3>
	<br />
	{% if todayslessonslots %}
		 <table class="data">
		 <tr><th>Start Time</th><th>Status</th><th>Type</th><th>Student(s)</th></tr>
		 	{% for lessonslot in todayslessonslots %}
		 		<tr class="{% cycle even,odd %}">
		 			<td><a href="{% url view_lessonslot lessonslot_id=lessonslot.id %}">{{lessonslot.start_time|time:"g:i a"}}</a></td>
		 			<td>{{lessonslot.lesson.status}}</td>
		 			{% if user.is_staff %}
		 			<td>{{lessonslot.lesson.lesson_type}}</td>
		 			<td>{% for student in lessonslot.lesson.students.all %}{{student.first_name}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
		 			{% endif %}
		 		</tr>
		 	{% endfor %}
		 </table>
		<br />
	{% else %}
		<h3>No Lessons On This Day</h3>
	{% endif %}
	<br />
	<a href="{% url view_season_bymonth season_id=season.id, display_month=display_date.month %}">Back to Calendar</a>
{% endblock %}

schedule/templates/schedule/household_detail.html
{% extends 'schedule/base_manage.html' %}

{% block title %}Household Detail{% endblock %}

{% block manage_content %}
	<h2>Household Details:</h2>
	
	<h3>Parents:</h3><br />
		{% if parents %}
		<table class="data">
			<tr><th>Name</th><th>Phone</th><th>Email</th><th>Reg Form</th></tr>
			{% for parent in parents %}
			<tr class="{% cycle even,odd %}">
				<td><a href="{% url view_parent parent_id=parent.id %}">{{ parent.first_name }} {{ parent.last_name }}<a></td>
				<td>{{ parent.phone_number }}</td>
				<td>{{ parent.email }}</td>
				<td class="{% if parent.has_registrationform %}{% else %}error{% endif %}">{% if parent.has_registrationform %} Yes {% else %} No {% endif %}</td>
				<td><a href="{% url edit_parent parent_id=parent.id %}">Edit</a></td>
			</tr>
			{% endfor %}
		</table>
		{% else %}
			<em>No Parents</em>
		{% endif %}
		<br />
		<a href="{% url add_parenttohousehold household_id=household.id %}">Add Parent</a>
		<br />
		<br />
	<h3>Students:</h3><br />
		{% if students %}
		<table class="data">
		<tr><th>Name</th><th>Age</th><th>Liability Form</th></tr>
			{% for student in students %}
			<tr class="{% cycle even,odd %}">
				<td><a href="{% url view_student student_id=student.id %}">{{ student.first_name }} {{ student.last_name }}</td>
				<td>{{ student.birth_date|timesince }}</td>
				<td class="{% if student.has_liabilityform %}{% else %}error{% endif %}">{% if student.has_liabilityform %} Yes {% else %} No {% endif %}</td>
				<td><a href="{% url edit_student student_id=student.id %}">Edit</a></td>
			</tr>
			{% endfor %}
		</table>
		{% else %}
			<em>No Students</em>
		{% endif %}
		<br />
		<a href="{% url add_studenttohousehold household_id=household.id %}">Add Student</a>
		<br />
		<br />
	
	<h3>Household Lessons:</h3>
	{% if household_lessons %}
		<table class="data">
			<tr><th>Day</th><th>Date</th><th>Start Time</th><th>Type</th><th>Status</th><th>Students</th></tr>
		{% for lesson in household_lessons %}
			<tr class="{% cycle even,odd %}">
				<td>{{ lesson.lessonslot_set.all.0.start_datetime|date:"D" }}</td>
				<td><a href="{% url view_lessonslot lessonslot_id=lesson.lessonslot_set.all.0.id %}">{{ lesson.lessonslot_set.all.0.start_datetime|date:"m/d/y" }}</a></td>
				<td>{{ lesson.lessonslot_set.all.0.start_time|time:"g:i a" }}</td>
				<td>{{ lesson.lesson_type }}</td>
				<td>{{ lesson.status }}</td>
				<td>{% for student in lesson.students.all %}{{ student.first_name }}{% if not forloop.last %},{% endif %} {% endfor %}</td>
			</tr>
		{% endfor %}
		</table>
	{% else %}
	<em>There are no scheduled lessons for this household.</em>
	{% endif %}
{% endblock %}

schedule/templates/schedule/household_list.html
{% extends 'schedule/base_manage.html' %}

	
{% block manage_content %}
	{% for household in object_list %}
		{% for parent in household.parent_set.all[:1] %} {{ parent.first_name }} {{parent.last_name }}<br />{% endfor %}
	{% endfor %}
{% endblock %}

schedule/templates/schedule/lessonslot_detail.html
{% extends 'schedule/base_manage.html' %}

{% block title %}Viewing {{ lessonslot.datetime|date:"n/j/y" }} {{ lessonslot.start_date|time:"g:i a" }}{% endblock %}

{% block manage_content %}
<h2> Lessonslot Detail:</h2>
<table class="detail">
	<tr>
		<th>Date:</th>
		<td>{{ lessonslot.start_datetime|date:"D M j Y" }}</td>
	</tr>
	<tr>
		<th>Time:</th> 
		<td>{{ lessonslot.start_datetime|time:"g:i a" }} - {{ lessonslot.end_datetime|time:"g:i a" }}</td>
	</tr>
	<tr>
		<th>Instructor:</th> 
		<td>{% firstof lessonslot.instructor "TBD" %}</td>
	</tr>
	<tr>
		<th>Status:</th> 
		<td>{{lessonslot.status}}</td>
	</tr>
</table>
	
	{% if lessonslot.lesson %}<br />
	<h3>Lesson Information:</h3>
	<a href="{% url delete_lesson lesson_id=lessonslot.lesson.id %}">Delete Lesson</a>
	 <a href="{% url edit_lesson lesson_id=lessonslot.lesson.id %}">Edit Lesson</a>
		<div id="lessonslotdetail_students">
		<table class="detail">
			<tr>
				<th>Status</th>
				<td>{{ lessonslot.lesson.status }}</td>
			</tr>
			<tr>
				<th>Type:</th>
				<td>{{ lessonslot.lesson.lesson_type }}</td>
			</tr>
			<tr>
				<th>Students:</th>
				<td>
				{% for student in lessonslot.lesson.students.all %}
					<a href="{% url view_household household_id=student.household.id %}">{{ student.first_name }} {{ student.last_name }}</a>
					<a href="{% url remove_studentfromlesson lesson_id=lessonslot.lesson.id, student_id=student.id %}">Remove</a><br />
				{% endfor %}
				</td>
			</tr>
			{% if lessonslot.intructor %}
			<tr>
				<th>Instructor:</th>
				<td>{{ lessonslot.instructor.first_name }} {{ lessonslot.intructor.last_name }}</td>
			</tr>
			{% endif %}
			</tr>
		</table>
			<a class="floatright" href="{% url add_studenttolesson lesson_id=lessonslot.lesson.id %}">Add Student</a>
			<br /><br />
		</div>
		
	{% endif %}
	
	{% if not lessonslot.lesson %}
		{% ifequal lessonslot.status "Open" %}
		<a href="/schedule/lesson/add">Add Lesson</a>
		{% endifequal %}
	{% endif %}
	
	{% ifequal lessonslot.status "Open" %}
		<a href="/schedule/lessonslot/{{lessonslot.id}}/close">Close Slot</a>
	{% endifequal %}
	
	{% ifequal lessonslot.status "Closed" %}
		<a href="/schedule/lessonslot/{{lessonslot.id}}/open">Open Slot</a>
	{% endifequal %}
	<br /><br />
	<a href="/schedule/season/{{ lessonslot.season.id }}/view/month/{{ lessonslot.start_datetime|date:"m" }}/">Back to Calendar</a>
{% endblock %}

schedule/templates/schedule/month_cal.html
<!--TODO: Change these urls to be dynamic using  url -->
	{% if user.is_staff %}
		<a class="floatright" href="{% url manage_schedule %}">Back to Management Dashboard</a>
	{% endif %}
<div id="calendar_controls">
	<a class="prev_month" href="/schedule/season/{{ season.id }}/view/month/{{ prev_month }}">Prev Month</a>
	<h1 class="monthtitle"><span class="monthtitle">{{ current_month }}</span></h1>
	<a class="next_month" href="/schedule/season/{{ season.id }}/view/month/{{ next_month }}">Next Month</a>
</div>

<div id="instructor_key">
	<span class="instructor_purple">Teacher Candace</span><br />
	<span class="instructor_blue">Teacher Hillary</span><br />
	<span class="instructor_orange">Teacher Alyssa</span><br />
</div>
<div class="note">Note: Make-up lessons are not allowed, please attend all of your scheduled lessons.</div>
<table class="season_month_cal">
	{% for week in calendar %}
		<tr>
			{% for day in headers %}
				<th class="center {{ day|date:"D"|slice:":3" }}">{{ day|date:"D"|slice:":3" }}</th>
			{% endfor %}
		</tr>
		<tr>
			{% for d in week %}
				{% if perms.schedule.can_viewfullschedule %}
					<td class="textright {{ d.day|date:"D"|slice:":3" }} date"><a href="{% url view_season_byday year=d.day.year, month=d.day.month, day=d.day.day %}">{{ d.day|date:"d" }}</a></td>
				{% else %}
					<td class="textright {{ d.day|date:"D"|slice:":3" }} date">{{ d.day|date:"d" }}</td>
				{% endif %}
			{% endfor %}
		</tr>
		<tr>
		{% for day in week %}
		<td class="{{ day.day|date:"D"|slice:":3" }} {% ifequal day.day today %}today{% endifequal %}">
		<!-- lesson actually means lessonslot here -->
			{% for lesson in day.lessons %}
				<!--TODO: Change these urls to be dynamic using  url -->
				{% if perms.schedule.can_viewfullschedule %}<a href="/schedule/lessonslot/{{lesson.id}}/view/">{% endif %}
					{% ifequal lesson.status "Closed" %}
						<span class="calendar_lesson_closed">
					{% else %}
						<span class="{% ifequal lesson.instructor.first_name "Hillary" %}instructor_blue{% endifequal %}
							{% ifequal lesson.instructor.first_name "Alyssa" %}instructor_orange{% endifequal %}
							{% ifequal lesson.instructor.first_name "Candace" %}instructor_purple{% endifequal %}">
					{% endifequal %}
						{{ lesson.start_datetime|time:"g:i A" }} -</span>
					<span class="{% ifequal lesson.status "Closed" %}calendar_lesson_closed{% endifequal %}
						{% ifequal lesson.status "Booked" %}calendar_lesson_booked{% endifequal %}
						{% ifequal lesson.status "Open" %}calendar_lesson_open{% endifequal %}">
						{% if not lesson.lesson.status %}{{ lesson.status }}
						{% else %}{{ lesson.lesson.status }}
						{% endif %}
					</span>
				{% if perms.schedule.can_viewfullschedule %}</a>{% endif %}
				<br />
			{% endfor %}
			<br />
		</td>
		{% endfor %}
		</tr>
	{% endfor %}
</table>
<div id="calendar_controls_footer">
	<a class="prev_month" href="/schedule/season/{{ season.id }}/view/month/{{ prev_month }}"><< Prev Month</a> - 
	<a class="next_month" href="/schedule/season/{{ season.id }}/view/month/{{ next_month }}">Next Month >></a>
</div>

schedule/templates/schedule/parent_detail.html
{% extends 'schedule/base_manage.html' %}

{% block title %}Parent Detail{% endblock %}

{% block col2 %}
	<h2>Parent Details:</h2>
	<a class="floatright" href="{% url stswim.schedule.admin_views.editparent parent_id=parent.id %}">Edit</a>
	
	<table class="detail">
		<tr>
			<th>Name:</th>
			<td>{{ parent.first_name }} {{parent.last_name }}</td>
		</tr>
		<tr>
			<th>Phone:</th> 
			<td>{{ parent.phone_number }}</td>
		</tr>
		{% if parent.email %}
		<tr>
			<th>Email:</th>
			<td>{{ parent.email }}</td>
		</tr>
		{% endif %}
		<tr>
			<th>Address:</th>
			<td class="address">
				{{ parent.address }}<br />
				{% if parent.address2 %}{{ parent.address2 }}{% endif %}<br />
				{{ parent.city }}, {{ parent.state }} {{ parent.zip_code }}<br />
			</td>
		</tr>
	</table>
	<a href="{% url view_household household_id=parent.household.id %}">Back to Household</a>
{% endblock %}

schedule/templates/schedule/seasonview.html
{% extends 'main1col.html' %}

{% load schedule_tags %}

{% block title %}Viewing {{season.name}} Season{% endblock %}

{% block singlecol %}
	{% season_month_cal %}
{% endblock %}